In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
csv_train_path = '/content/drive/My Drive/ML_Datasets/train.csv'
csv_test_path = '/content/drive/My Drive/ML_Datasets/test.csv'
column_names = [
    'age', 'workclass', 'fnlwgt', 'education', 'education-num',
    'marital-status', 'occupation', 'relationship', 'race', 'sex',
    'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income'
]
train_df = pd.read_csv(csv_train_path)
test_df = pd.read_csv(csv_test_path)

print(len(train_df))
len(test_df)

32174

16668

In [ ]:
train_df.info()
train_df['income'] = train_df['income'].str.rstrip('.')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32174 entries, 0 to 32173
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32174 non-null  int64
 1   workclass       31211 non-null  object
 2   fnlwgt          32174 non-null  int64
 3   education       32174 non-null  object
 4   education-num   32174 non-null  int64
 5   marital-status  32174 non-null  object
 6   occupation      31208 non-null  object
 7   relationship    32174 non-null  object
 8   race            32174 non-null  object
 9   sex             32174 non-null  object
 10  capital-gain    32174 non-null  int64
 11  capital-loss    32174 non-null  int64
 12  hours-per-week  32174 non-null  int64
 13  native-country  31900 non-null  object
 14  income          32174 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
train_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,65,Self-emp-not-inc,131417,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,1797,0,21,United-States,<=50K
1,17,Private,111593,11th,7,Never-married,Sales,Own-child,White,Female,0,0,8,United-States,<=50K
2,25,Private,251854,Some-college,10,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,40,Jamaica,<=50K
3,60,State-gov,165827,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688,0,60,United-States,>50K
4,32,Private,204374,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [ ]:
train_df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32174.000000,3.217400e+04,32174.000000,32174.000000,32174.000000,32174.000000
mean,38.596911,1.899208e+05,10.057500,1075.397899,88.705974,40.272270
std,13.799781,1.051263e+05,2.573071,7423.181537,405.498367,12.469547
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176740e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.784560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.381860e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.268339e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
train_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,65,Self-emp-not-inc,131417,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,1797,0,21,United-States,<=50K
1,17,Private,111593,11th,7,Never-married,Sales,Own-child,White,Female,0,0,8,United-States,<=50K
2,25,Private,251854,Some-college,10,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,40,Jamaica,<=50K
3,60,State-gov,165827,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688,0,60,United-States,>50K
4,32,Private,204374,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [ ]:
test_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,34,Private,122116,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States
1,36,State-gov,223020,Some-college,10,Divorced,Other-service,Unmarried,Black,Female,0,0,20,United-States
2,59,Self-emp-not-inc,165867,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,25,United-States
3,59,Private,453067,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,36,United-States
4,36,Private,49657,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States

In [ ]:
missing_values = train_df.isnull().sum()
missing_values

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
income              0
dtype: int64

In [ ]:
missing_values = test_df.isnull().sum()
missing_values

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
dtype: int64

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
def train_and_generate_submission(train_df, test_df, categorical_columns, output_path='submission.csv'):
    """
    Entrena con train_df y genera predicciones para test_df sin columna target

    Parameters:
    -----------
    train_df : DataFrame
        Dataset de entrenamiento con columna 'income'
    test_df : DataFrame
        Dataset de test sin columna 'income'
    categorical_columns : list
        Lista de columnas categóricas
    output_path : str
        Ruta para guardar el archivo de submission
    """
    # Copia de los dataframes
    train = train_df.copy()
    test = test_df.copy()

    print("Shapes iniciales:")
    print(f"Train shape: {train.shape}")
    print(f"Test shape: {test.shape}")

    # Convertir target a formato numérico
    label_encoder = LabelEncoder()
    train['income'] = label_encoder.fit_transform(train['income'])

    # Separar features y target en train
    X_train = train.drop('income', axis=1)
    y_train = train['income']

    # Crear el preprocesador
    categorical_transformer = Pipeline(steps=[
        ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', categorical_transformer, categorical_columns)
        ],
        remainder='passthrough',
        sparse_threshold=0
    )

    # Crear y entrenar el pipeline
    model = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
    ])

    print("\nEntrenando modelo...")
    model.fit(X_train, y_train)

    # Generar predicciones para el test
    print("\nGenerando predicciones...")
    predictions_numeric = model.predict(test)
    predictions = label_encoder.inverse_transform(predictions_numeric)

    # Crear DataFrame de submission
    submission = pd.DataFrame({
        'ID': range(len(predictions)),
        'income': predictions
    })

    # Guardar archivo
    submission.to_csv(output_path, index=False)

    print(f"\nSubmission guardada en {output_path}")
    print("\nPrimeras 5 filas del archivo de submission:")
    print(submission.head())

    print("\nDistribución de predicciones:")
    print(submission['income'].value_counts(normalize=True).round(3))

    return model, submission

# Ejemplo de uso
categorical_columns = [
    'workclass', 'education', 'marital-status', 'occupation',
    'relationship', 'race', 'sex', 'native-country'
]

# Entrenar y generar submission
model, submission = train_and_generate_submission(train_df, test_df, categorical_columns)

Shapes iniciales:
Train shape: (32174, 15)
Test shape: (16668, 14)

Entrenando modelo...

Generando predicciones...

Submission guardada en submission.csv

Primeras 5 filas del archivo de submission:
   ID income
0   0  <=50K
1   1  <=50K
2   2  <=50K
3   3  <=50K
4   4   >50K

Distribución de predicciones:
income
<=50K    0.796
>50K     0.204
Name: proportion, dtype: float64